### ISSUE TITLE
how to stop center dot?

### ISSUE THREAD

**Issue by BattleHook** [DerKuehneKollege/center-dot#1]
Can you also make an application to stop centerdot? Or is it a commandflag?

**Comment by DerKuehneKollege** [comment]
CenterDot is accessible as a notification icon via the Windows systray. Just right click on the icon an you can Exit the application via the context menu.

![grafik](https://user-images.githubusercontent.com/5735788/216760274-e2eb0a31-dba1-41bf-b553-1691df7b9671.png)

**Comment by BattleHook** [comment]
Thank you. Maybe add this info to the readme ??

Just one little note: Center Dot shows in the Windows Systray only if you start Center Dot as admin.

**Comment by DerKuehneKollege** [comment]
> Thank you. Maybe add this info to the readme ??
> 
> Just one little note: Center Dot shows in the Windows Systray only if you start Center Dot as admin.

Good idea. I updated the manual.
