### ISSUE TITLE
No EXE file?

### ISSUE THREAD

**Issue by NoEXEFile** [DerKuehneKollege/center-dot#2]
No where in the code is there a .exe file from what I have seen.
I have gone through every folder and there is no EXE file. help.

**Comment by DerKuehneKollege** [comment]
Sorry, I build the release in a wrong way. Now the program package including the exe file can be downloaded here:

https://github.com/DerKuehneKollege/center-dot/releases/download/v1.0/CenterDot-v1.0.zip

**Comment by NoEXEFile** [comment]
Thank you!
