### ISSUE TITLE
how to use!

### ISSUE THREAD

**Issue by damien885** [DerKuehneKollege/center-dot#3]
how to use!

**Comment by Pacdizzle** [comment]
[Download](https://github.com/DerKuehneKollege/center-dot/releases/download/v1.0/CenterDot-v1.0.zip) the .zip file and extract it anywhere you like. Open the folder and double click the CenterDot.exe

**Comment by DerKuehneKollege** [comment]
check da readme!

https://github.com/DerKuehneKollege/center-dot#usage
