### ISSUE TITLE
Hide the cosshair with key cobo

### ISSUE THREAD

**Issue by jsniperx** [DerKuehneKollege/center-dot#5]
Please could you make a version where you can hide the crosshair with a key combination rather than having to tab out of a game t and go to the system tray to hide it please? Thanks.

**Comment by DerKuehneKollege** [comment]
There already is an undocumented key combo.
You can press 
<kbd>Ctrl</kbd> + <kbd>H</kbd>
to toggle show/hide the crosshair.

I will add it to the documentation.

**Comment by worldsprayer** [comment]
The keybind does not appear to function.  It does not work in game, out of game, on desktop or in any window I have tried.
Edit: Disregard.  If you run the program from the zip, the functionality is disabled.
